name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: arch-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt-get install libevent-dev
    - name: Build lib/
      run: mkdir build && cd build/ && cmake .. && make

  test:

    runs-on: arch-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt-get install libevent-dev
    - name: Test lib/
      run: mkdir build && cd build/ && cmake .. && make test
